---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
#E4tools

E4tools is an early-release set of tools that you can use to automate your workflow for analyzing EDA data that comes from the Empatica E4. You can run these functions consecutively. 

##What can you do now with E4tools?
There are currently four tools, all of which are part of the EDA workflow (acc. workflow coming soon):

**E4_EDA_Process.part1.ExtractRawEDA**, which allows you extract and filter EDA data. It will output raw data, filtered data (using user-specified high and low pass filters + a butterworth filter), and filtered + feature-scaled ([0,1]) data. It will also provide summary data at the participant and session level.

**E4_EDA_Process.part2.ExtractButtonPresses**, which allows you extract button pressess and remove pressess that are within a certain number of minutes before the end of a session or that are too close to another button press.

**E4_EDA_Process.part3.MatchPressesToEDA**, which allows you to extract the data that are within X minutes before and/or after a button press.

**E4_EDA_Process.part4.BinMatchedEDA**, which allows you to bin the data that has been matched to the button pressess (from step 3).

##How do I install E4tools?
`install.packages("E4tools")`

##Funding
This package was created to support data from projects R34MH113757-01A1 and R21MH115293 to Evan M. Kleiman. 

